using System;
using Microsoft.WindowsAzure.Storage.Table;

namespace SocialLinker.Core.CloudStorageTables
{
    public class UserInfoFields : TableEntity
    {
        public string Platform => PartitionKey;
        public string User_ID => RowKey;
        public DateTime? Date_Started { get; set; }
        public string Account_Activated { get; set; }
        public string Profile_Theme { get; set; }
        public string Decor_Owned { get; set; }
        public string Decor_Setting { get; set; }
        public string Shop_Sort { get; set; }
        public int Level { get; set; }
        public int Total_Exp { get; set; }
        public DateTime? Last_Message_Cooldown { get; set; }
        public DateTime? Loop_Point_Hour { get; set; }
        public DateTime? Loop_Point_Day { get; set; }
        public int Hourly_Exp_Gained { get; set; }
        public int Daily_Exp_Gained { get; set; }
        public int Hourly_Cap_Counter { get; set; }
        public DateTime? Time_Out_Start { get; set; }
        public int Time_Out_Duration { get; set; }
        public string First_Level_Msg_Sent { get; set; }
        public string First_Rank_Msg_Sent { get; set; }
        public string All_Ranks_Maxed_Msg_Sent { get; set; }
        public int Level_Resets { get; set; }
        public int Proficiency { get; set; }
        public int Diligence { get; set; }
        public int Expression { get; set; }
        public int Proficiency_Rank { get; set; }
        public int Diligence_Rank { get; set; }
        public int Expression_Rank { get; set; }
        public int Daily_Proficiency_Gained { get; set; }
        public string Daily_Diligence_Gained { get; set; }
        public int Daily_Expression_Gained { get; set; }
        public int Diligence_Multiplier { get; set; }
        public int P_Medals { get; set; }
        public string City { get; set; }
        public string Level_Up_Notifications { get; set; }
        public string Rank_Up_Notifications { get; set; }
        public string Content_Filter { get; set; }
        public string VC_P1 { get; set; }
        public string VC_P2IS { get; set; }
        public string VC_P2EP { get; set; }
        public string VC_P3 { get; set; }
        public string VC_P4 { get; set; }
        public string VC_P5 { get; set; }
        public string CustomSpriteSets { get; set; }
        public string P1_PSX_TS_Wallpaper { get; set; }
        public string P1_PSX_TS_Moon_HUD { get; set; }
        public string P1_PSX_TS_Position { get; set; }
        public string P1_PSX_TS_BG_Darken { get; set; }
        public string P1_PSX_TS_Localized_Revelations_Names { get; set; }
        public string P1_PSX_TS_Consistent_Names { get; set; }
        public string P1_PSP_TS_Moon_HUD { get; set; }
        public string P1_PSP_TS_Position { get; set; }
        public string P1_PSP_TS_BG_Darken { get; set; }
        public string P2IS_PSX_TS_Wallpaper { get; set; }
        public string P2IS_PSX_TS_Invert { get; set; }
        public string P2IS_PSX_TS_Position { get; set; }
        public string P2IS_PSX_TS_Sprite_Flip { get; set; }
        public string P2IS_PSX_TS_Localized_Revelations_Names { get; set; }
        public string P2IS_PSP_TS_Invert { get; set; }
        public string P2IS_PSP_TS_Position { get; set; }
        public string P2IS_PSP_TS_Sprite_Flip { get; set; }
        public string P2EP_PSX_TS_Wallpaper { get; set; }
        public string P2EP_PSX_TS_Invert { get; set; }
        public string P2EP_PSX_TS_Position { get; set; }
        public string P2EP_PSX_TS_Sprite_Flip { get; set; }
        public string P2EP_PSX_TS_Localized_Revelations_Names { get; set; }
        public string P2EP_PSP_TS_Window_Color { get; set; }
        public string P2EP_PSP_TS_Invert { get; set; }
        public string P2EP_PSP_TS_Position { get; set; }
        public string P2EP_PSP_TS_Sprite_Flip { get; set; }
        public string P3F_TS_HUD { get; set; }
        public string P3F_TS_Nav { get; set; }
        public string P3P_TS_Color { get; set; }
        public string P3P_TS_HUD { get; set; }
        public string P3P_TS_Position { get; set; }
        public string P3P_TS_Dual { get; set; }
        public string P4_PS2_TS_HUD { get; set; }
        public string P4G_TS_HUD { get; set; }
        public string P4AU_TS_Scene_Type { get; set; }
        public string P4AU_TS_Auto_Advance { get; set; }
        public string P4AU_TS_Panel { get; set; }
        public string P4AU_TS_Position { get; set; }
        public string P4AU_TS_Dual { get; set; }
        public int P4AU_TS_Nav_BG { get; set; }
        public string P4AU_TS_Phone_BG { get; set; }
        public string P4AU_TS_Highlight { get; set; }
        public string P4D_TS_Scene_Type { get; set; }
        public string P4D_TS_Auto_Advance { get; set; }
        public string P4D_TS_Position { get; set; }
        public string P4D_TS_Dual { get; set; }
        public int P4D_TS_Nav_Call_Location { get; set; }
        public string P5_PS4_TS_HUD { get; set; }
        public string P5_PS4_TS_Border { get; set; }
        public string P5_PS4_TS_Panel { get; set; }
        public string P5R_TS_HUD { get; set; }
        public string P5R_TS_Border { get; set; }
        public string P5R_TS_Panel { get; set; }
        public string P5R_TS_Caller_Toggle { get; set; }
        public string P5R_TS_Caller_Location { get; set; }
        public string P5S_TS_Controller_Type { get; set; }
        public string P5S_TS_Skip_Button { get; set; }
        public string P5S_TS_Auto_Advance { get; set; }
        public string P5S_TS_Scene_Border { get; set; }
        public string P5S_TS_Date_Location_Layout { get; set; }
        public string P5S_TS_Location_Icon { get; set; }
        public string P5S_TS_Watermark { get; set; }
        public string BBTAG_TS_Header { get; set; }
        public string BBTAG_TS_Position { get; set; }
        public string BBTAG_TS_BG_Blur { get; set; }
        public string Display_Names_Sort { get; set; }
        public string Setting_Sheet_Order { get; set; }
        public string Setting_BG_Color { get; set; }
        public string Setting_BG_Upload { get; set; }
        public string P1_PSX_Resolution { get; set; }
        public string P1_PSX_Scale { get; set; }
        public string P1_PSP_Resolution { get; set; }
        public string P1_PSP_Scale { get; set; }
        public string P2IS_PSX_Resolution { get; set; }
        public string P2IS_PSX_Scale { get; set; }
        public string P2IS_PSP_Resolution { get; set; }
        public string P2IS_PSP_Scale { get; set; }
        public string P2EP_PSX_Resolution { get; set; }
        public string P2EP_PSX_Scale { get; set; }
        public string P2EP_PSP_Resolution { get; set; }
        public string P2EP_PSP_Scale { get; set; }
        public string P3F_Resolution { get; set; }
        public string P3F_Scale { get; set; }
        public string P3P_Resolution { get; set; }
        public string P3P_Scale { get; set; }
        public string P4_PS2_Resolution { get; set; }
        public string P4_PS2_Scale { get; set; }
        public string P4AU_Resolution { get; set; }
        public string P4AU_Scale { get; set; }
        public string P4D_Resolution { get; set; }
        public string P4D_Scale { get; set; }
        public string Auto_Delete_Commands { get; set; }
        public string Auto_Delete_Error_Messages { get; set; }

        // Calendar
        //public string P1_PSX_Manual_Cycle_Toggle { get; set; }
        //public string P1_PSX_Manual_Cycle_Moon_Phase { get; set; }
        //public string P1_PSP_Manual_Cycle_Toggle { get; set; }
        //public string P1_PSP_Manual_Cycle_Moon_Phase { get; set; }
        //public string P3F_Manual_Cycle_Toggle { get; set; }
        //public string P3F_Manual_Cycle_Moon_Phase { get; set; }
        //public string P3P_Manual_Cycle_Toggle { get; set; }
        //public string P3R_Manual_Cycle_Toggle { get; set; }
        //public string P4_PS2_Manual_Cycle_Toggle { get; set; }
        //public string P4G_Manual_Cycle_Toggle { get; set; }
        //public string P5_PS3_Manual_Cycle_Toggle { get; set; }
        //public string P5R_Manual_Cycle_Toggle { get; set; }
        //public string P5R_Manual_Cycle_Month { get; set; }
        //public string P5R_Manual_Cycle_Day { get; set; }
        //public string P5R_Manual_Cycle_Day_of_Week { get; set; }
        //public string P5R_Manual_Cycle_Time_of_Day { get; set; }
        //public string P5S_Manual_Cycle_Cycle_Toggle { get; set; }
        //public string P5S_Manual_Cycle_Month { get; set; }
        //public string P5S_Manual_Cycle_Day { get; set; }
        //public string P5S_Manual_Cycle_Day_of_Week { get; set; }
        //public string P5S_Manual_Cycle_Time_of_Day { get; set; }
    }
}
